-- SQL - STRUCTURED QUERY LANGUEGE (LINGUAGEM DE CONSULTA STRUTURADA)
-- SQL - BASEADO EM COMANDOS:
	-- DDL - DATA DEFINITION LANGUAGE (CRIAR, ALTERAR OU APAGAR BANCO DE DADOS E TABELAS)
	-- DML - DATA MANIPULATION LANGUAGE (CRIAR, ALTERAR OU APAGAR DADOS)
	-- DQL - DATA QUERY LANGUAGE (VER OS DADOS)
------------------------------------------------------------------------------------------------

-- PARA LEMBRAR EM QUAL BANCO DE DADOS ESTOU TRABALHANDO
USE ECommerce

-- CRIANDO UM BANCO DE DADOS
CREATE DATABASE ECommerce

-- PARA APAGAR BANCO DE DADOS E TABELAS --> DROP DATABASE ECommerce OU DROP TABLE ECommerce

-- CRIANDO UMA TABELA
-------------SUGESTAO: NOME SEMPRE NO SINGULAR E COMECAR COM LETRA MAIUSCULA
CREATE TABLE Cliente (
		
		IDCliente INT PRIMARY KEY IDENTITY, -- IDENTITY GERA A NUMERACAO DE ID AUTOMATICAMENTE
		NomeCompleto VARCHAR(150),  
		Email VARCHAR(100), 
		Telefone VARCHAR(20),
		Endereco VARCHAR(255),
		DataCadastro DATE
)

CREATE TABLE Pedido (

	IDPedido INT PRIMARY KEY IDENTITY,
	DataPedido DATE,
	Status VARCHAR (20),
	ValorTotal DECIMAL (18, 6),
	IDCliente INT FOREIGN KEY REFERENCES Cliente(IDCliente)
)

CREATE TABLE Pagamento (

	IDPagamento INT PRIMARY KEY IDENTITY,
	FormaPagamento VARCHAR (30),
	StatusPagamento VARCHAR (20),
	DataPagamento DATETIME,
	IDPedido INT FOREIGN KEY REFERENCES Pedido(IDPedido)
)

CREATE TABLE Produto (

	IDProduto INT PRIMARY KEY IDENTITY,
	NomeProduto VARCHAR (150),
	Preco DECIMAL (18, 6),
	EstoqueDisponivel INT,
	CategoriaProduto VARCHAR (100),
	Imagem VARCHAR (255)
)


CREATE TABLE ItemPedido (
	
	IDItemPedido INT PRIMARY KEY IDENTITY,
	Quantidade INT,
	IDProduto INT FOREIGN KEY REFERENCES Produto(IDProduto),
	IDPedido INT FOREIGN KEY REFERENCES Pedido(IDPedido)
)

